### ISSUE TITLE
Picovoice Issue: Bug on Windows 10 with x64

### ISSUE THREAD

**Issue by Symfomany** [Picovoice/picovoice#100]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

I train a WakeWord via Console of Picovoice.
![dsfdsf](https://user-images.githubusercontent.com/1421325/125258744-ecf54680-e2fe-11eb-803f-7e24d871d90f.PNG)

But it's not working in my Windows 10 X64 by CLI with this error in my console:

pv-mic-demo \
--keyword_file_path resources/porcupine/resources/keyword_files/windows/alpha.ppn \

### Actual behaviour

![sfddsf](https://user-images.githubusercontent.com/1421325/125258596-ccc58780-e2fe-11eb-8e61-e81bed9616de.PNG)

### Steps to reproduce the behaviour

Do you have this problem too ?

Thanks !!

**Comment by dbartle** [comment]
The Picovoice NodeJS bindings do not support Windows at this time. This behaviour is expected and documented (and the error message tells the story accurately). Unfortunately, NodeJS interop with native code makes this significantly more effort than one might think, which is why that support is absent at present.

If you would like to open a new issue requesting Windows support for NodeJS, please do so, and we will use that issue as a means to judge whether there is sufficient demand to prioritize it.
