### ISSUE TITLE
Speech to intent with wake word and manually

### ISSUE THREAD

**Issue by rutharaka4** [Picovoice/picovoice#437]
I'm trying to develop react native application which need to have
1. speech to intent with wake word 
2. Speech to intent with button click.

I tried with picovoice SDK and also with integrating procuipine and rhino SDK's as well but couldn't able to success.

Please share me a guide if the features is already exist. Since i couldn't able to find it from the documentations.

**Comment by mrrostam** [comment]
I don't think Picovoice SDK is suitable for your use case as it detects the occurrence of the custom wake word, and then activates its internal Speech-to-Intent engine automatically, and extracts the intent from the follow-on spoken command. So basically you have no control on the audio flow.

Since you also want to manually start the Rhino Speech-to-intent engine, I suggest using Porcupine and Rhino engines separately.

Please check out [Porcupine](https://picovoice.ai/docs/quick-start/porcupine-react-native/)  and [Rhino](https://picovoice.ai/docs/quick-start/rhino-react-native/)'s docs for React Native on our website for further information.

**Comment by rutharaka4** [comment]
What we are trying to do is, 

1. User will give command to a application after the wake word (e.g. **Computer**, I need help!)
2. Then application should give the voice response. (e.g. How can I help you ?)
3. Then user should be able to reply without the wake word (e.g. I need medical assistance)

Do you have a support this kind of conversation developments. Once the device gives the response picovoice automatically listen to the user voice response.  Please share me a guide if available

**Comment by mrrostam** [comment]
1. For the wake word detection, you can easily use Porcupine: [React Native Quick Start](https://picovoice.ai/docs/quick-start/porcupine-react-native/)
2. This step is basically only playing an audio stream, so no voice product is needed.
3. For this part, Rhino can do the job: [React Native Quick Start](https://picovoice.ai/docs/quick-start/rhino-react-native/)

**Comment by rutharaka4** [comment]
1. In the documentation for rhino manager, It has methods as 

await rhinoManager.start();
await rhinoManager.stop();

But when tried it gives an error as undefined and the available method is 
await rhinoManager.process();

is that the correct understanding ?

**Comment by mrrostam** [comment]
oh! That's a mistake in our docs; thanks for letting us know.

For now you can refer to the [Rhino's readme](https://github.com/Picovoice/rhino/tree/master/binding/react-native) until we update our website and fix the mistake.

**Comment by mrrostam** [comment]
The [React Native doc](https://picovoice.ai/docs/quick-start/rhino-react-native/) on our website is now updated to reflect the latest changes to our React Native SDK. I'm closng this issue as fixed but feel free to open another if you spot any more issues.

**Comment by rutharaka4** [comment]
Hi Team,

Doing a POC now and will enroll one the POC is succeed. So Is it possible to extend the trial period ?
