### ISSUE TITLE
"Invalid Argument" Message When Using Older KEYWORD Array

### ISSUE THREAD

**Issue by nelsonii** [Picovoice/picovoice#548]
In general, do the Keyword arrays change per version? I like using the default "picovoice" since I'm not limited by keyword generation limitations.

* Generated a Context file for a new board (Arduino Nano 33 BLE )
* Tried file with my existing code, was informed that versions didn't match. I coded to 2.1.
* Updated Arduino library to 2.2. Used new context file. Used existing keyword (generic "picovoice").
* Kept getting "invalid argument" on pv_picovoice_init
* Finally traced it to the Keyword Array -- I had been using the "picovoice" example (not "hey computer")
* Dug into the updated Porcupine examples for multiple keywords, saw that the hex codes for V2.1 to V2.2 differ.

So, I figured out my problem. :-) But the "invalid argument" message wasn't helping much -- "bad keyword version" or something would have saved me some time.

**Comment by laves** [comment]
@nelsonii, thank you for your feedback. Yes - keywords, contexts, and models are all locked to versions. We recently released v2.2, which is why your project went out of sync with its v2.1 resources. The point is well taken that our error messages are not descriptive on many platforms and we are looking at ways to improve that in a future release, but unfortunately cannot commit to timelines on it.

**Comment by mrrostam** [comment]
@nelsonii, thank you for bringing this to our attention. As mentioned by @laves, For some invalid input arguments, we cannot really provide any details. However, in your particular case, where the library version does not match the input keyword or context models, we do have a special error log that will provide you with specific details regarding the problem. Unfortunately, there is currently an issue that is preventing the library from logging any information, which is why you did not receive any details. We are actively working on a solution and will release new packages soon. We apologize for any confusion caused.

**Comment by mrrostam** [comment]
The issue has been resolved, and the new package (v2.2.1) is now available. If you input an incorrect version of either the keyword or context models, you should receive an error message in the serial monitor stating "[ERROR]: Model file version is `something` but library version is `something else`". Could you please test it and confirm this behavior?

**Comment by nelsonii** [comment]
Thanks for looking into this so quickly. 

Before I update -- will this invalidate my v2.2.0 models? -- will I have to regenerate them on the portal? 

I'm on the free tier, so I don't have a lot of leeway.

**Comment by mrrostam** [comment]
No worries, updating won't invalidate your v2.2.0 models. They should still be valid for all v2.2.x packages, so you don't have to regenerate them.

**Comment by nelsonii** [comment]
Excellent. Thank you.

Confirmed: Upgrading to the 2.2.1 Arduino library did not invalidate my 2.2.0 context model.

Confirmed: Upgrading to 2.2.1 presents a more detailed debugging message. Very helpful! Thank you.
