### ISSUE TITLE
[question] is it possible disable IOS AVAudioSession handling to prevent conflict with flutter_webrtc

### ISSUE THREAD

**Issue by fullflash** [Picovoice/picovoice#671]
hi. i did not find any support form in your official web site.
We would like to use this package as replacement for speech_to_text flutter plugin.
In our project we are using mediasoup flutter client that depend on flutter_web_rtc we would like to know if it is possible to prevent conflict ios AVAudioSession setting category with your plugin.
Thanks

**Comment by laves** [comment]
@fullflash - it is not possible as our plugin requires audio capture to function. You can always change the category yourself, but that may lead to our plugin no longer receiving audio. Mixing audio plugins in Flutter often leads to conflicts like this. If you require a custom audio configuration, I'd recommend using `picovoice` instead of `picovoice_manager` and managing the audio capture through your application code.
